### PR TITLE
Change license to MIT

### PR DESCRIPTION
**Pull request by natesales**
Pathvector is currently licensed under the GNU GPLv3 license, which is comparatively restrictive in what it permits users to do with the software. I'm proposing that we relicense Pathvector to the permissive [MIT license](https://mit-license.org/) to allow everyone to use, change, and modify Pathvector more freely than is currently permitted under the GPL. In order to do so, each contributor must agree to the change. If you agree to relicense Pathvector under MIT, please comment below and I'll check you off this list.

Contributors as of June 17, 2022 (a7929c016b232492cbdeeeb980d1199602b0d5f7):
- [x] @natesales 
- [x] @hamptonmoore 
- [x] @netfreak98 
- [x] @JustAB0x 
- [x] @samip5 
- [x] @steveyiyo 
- [x] @nickhilliard 

As always, I appreciate each and every contributor to this project, so again, thank you for your help along the way :)

### CODE REVIEW

**Comment by steveyiyo** [comment]
I agree with this change, thanks @natesales!

**Comment by samip5** [comment]
I agree with this. @natesales

**Comment by hamptonmoore** [comment]
lgtm

**Comment by nickhilliard** [comment]
lgtm

**Comment by JustAB0x** [comment]
Agreed!

**Comment by JustAB0x** [comment]
Agreed :)!

**Comment by netfreak98** [comment]
Ack :)

**Comment by natesales** [comment]
Thanks everyone!

**Pull request merged**
